<?php
$ul_system_config = array(
    array(
        "name" => "alisms_access_key_id",
        "group" => "sms",
        "value" => "填你的",
        "remark" => "阿里大于公钥",
        "sort" => 0,
    ),
    array(
        "name" => "alisms_access_key_secret",
        "group" => "sms",
        "value" => "填你的",
        "remark" => "阿里大鱼私钥",
        "sort" => 0,
    ),
    array(
        "name" => "upload_type",
        "group" => "upload",
        "value" => "local_public",
        "remark" => "当前上传方式 local_public,alioss,qnoss,txoss）",
        "sort" => 0,
    ),
    array(
        "name" => "upload_allow_ext",
        "group" => "upload",
        "value" => "jpg,jpeg,png,gif,bmp,doc,docx,xls,xlsx,ppt,pptx,pdf,zip,rar,7z,txt,mp3,wma,wav,mid,m4a,mp4,avi,wmv,3gp,flv,webp,svg,ico",
        "remark" => "允许上传的文件类型",
        "sort" => 0,
    ),
    array(
        "name" => "upload_allow_size",
        "group" => "upload",
        "value" => "1024000",
        "remark" => "允许上传的大小",
        "sort" => 0,
    ),
    array(
        "name" => "upload_allow_mime",
        "group" => "upload",
        "value" => "image/gif,image/jpeg,video/x-msvideo,text/plain,image/png",
        "remark" => "允许上传的文件mime",
        "sort" => 0,
    ),
    array(
        "name" => "upload_allow_type",
        "group" => "upload",
        "value" => "local_public,alioss,qnoss,txcos",
        "remark" => "可用的上传文件方式",
        "sort" => 0,
    ),
    array(
        "name" => "alioss_access_key_id",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "阿里云oss公钥",
        "sort" => 0,
    ),
    array(
        "name" => "alioss_access_key_secret",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "阿里云oss私钥",
        "sort" => 0,
    ),
    array(
        "name" => "alioss_endpoint",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "阿里云oss数据中心",
        "sort" => 0,
    ),
    array(
        "name" => "alioss_bucket",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "阿里云oss空间名称",
        "sort" => 0,
    ),
    array(
        "name" => "alioss_domain",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "阿里云oss访问域名",
        "sort" => 0,
    ),
    array(
        "name" => "logo_title",
        "group" => "site",
        "value" => "ulthon_admin",
        "remark" => "LOGO标题",
        "sort" => 0,
    ),
    array(
        "name" => "logo_image",
        "group" => "site",
        "value" => "/static/common/images/logo-2.png",
        "remark" => "logo图片",
        "sort" => 0,
    ),
    array(
        "name" => "site_name",
        "group" => "site",
        "value" => "ulthon_admin后台系统",
        "remark" => "站点名称",
        "sort" => 0,
    ),
    array(
        "name" => "site_ico",
        "group" => "site",
        "value" => "/favicon.ico",
        "remark" => "浏览器图标",
        "sort" => 0,
    ),
    array(
        "name" => "site_copyright",
        "group" => "site",
        "value" => "填你的",
        "remark" => "版权信息",
        "sort" => 0,
    ),
    array(
        "name" => "site_beian",
        "group" => "site",
        "value" => "填你的",
        "remark" => "备案信息",
        "sort" => 0,
    ),
    array(
        "name" => "site_version",
        "group" => "site",
        "value" => "2.0.0",
        "remark" => "版本信息",
        "sort" => 0,
    ),
    array(
        "name" => "sms_type",
        "group" => "sms",
        "value" => "alisms",
        "remark" => "短信类型",
        "sort" => 0,
    ),
    array(
        "name" => "miniapp_appid",
        "group" => "wechat",
        "value" => "填你的",
        "remark" => "小程序公钥",
        "sort" => 0,
    ),
    array(
        "name" => "miniapp_appsecret",
        "group" => "wechat",
        "value" => "填你的",
        "remark" => "小程序私钥",
        "sort" => 0,
    ),
    array(
        "name" => "web_appid",
        "group" => "wechat",
        "value" => "填你的",
        "remark" => "公众号公钥",
        "sort" => 0,
    ),
    array(
        "name" => "web_appsecret",
        "group" => "wechat",
        "value" => "填你的",
        "remark" => "公众号私钥",
        "sort" => 0,
    ),
    array(
        "name" => "txcos_secret_id",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "腾讯云cos密钥",
        "sort" => 0,
    ),
    array(
        "name" => "txcos_secret_key",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "腾讯云cos私钥",
        "sort" => 0,
    ),
    array(
        "name" => "txcos_region",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "存储桶地域",
        "sort" => 0,
    ),
    array(
        "name" => "txcos_bucket",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "存储桶名称",
        "sort" => 0,
    ),
    array(
        "name" => "qnoss_access_key",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "访问密钥",
        "sort" => 0,
    ),
    array(
        "name" => "qnoss_secret_key",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "安全密钥",
        "sort" => 0,
    ),
    array(
        "name" => "qnoss_bucket",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "存储空间",
        "sort" => 0,
    ),
    array(
        "name" => "qnoss_domain",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "访问域名",
        "sort" => 0,
    ),
    array(
        "name" => "txcos_domain",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "访问域名",
        "sort" => 0,
    ),
    array(
        "name" => "txcos_appid",
        "group" => "upload",
        "value" => "填你的",
        "remark" => "APPID",
        "sort" => 0,
    ),
    array(
        "name" => "file",
        "group" => "site",
        "value" => "",
        "remark" => "",
        "sort" => 0,
    ),
    array(
        "name" => "site_domain",
        "group" => "site",
        "value" => "http://admin.demo.ulthon.com",
        "remark" => "",
        "sort" => 0,
    )
);
return $ul_system_config;
