<?php
$ul_system_menu = array(
    array(
        "id" => 227,
        "pid" => 99999999,
        "title" => "后台首页",
        "icon" => "fa fa-home",
        "href" => "index/welcome",
        "params" => "",
        "target" => "_self",
        "sort" => 0,
        "status" => 1,
    ),
    array(
        "id" => 228,
        "pid" => 0,
        "title" => "系统管理",
        "icon" => "fa fa-cog",
        "href" => "",
        "params" => "",
        "target" => "_self",
        "sort" => 0,
        "status" => 1,
    ),
    array(
        "id" => 234,
        "pid" => 228,
        "title" => "菜单管理",
        "icon" => "fa fa-tree",
        "href" => "system.menu/index",
        "params" => "",
        "target" => "_self",
        "sort" => 10,
        "status" => 1,
    ),
    array(
        "id" => 244,
        "pid" => 228,
        "title" => "管理员管理",
        "icon" => "fa fa-user",
        "href" => "system.admin/index",
        "params" => "",
        "target" => "_self",
        "sort" => 12,
        "status" => 1,
    ),
    array(
        "id" => 245,
        "pid" => 228,
        "title" => "角色管理",
        "icon" => "fa fa-bitbucket-square",
        "href" => "system.auth/index",
        "params" => "",
        "target" => "_self",
        "sort" => 11,
        "status" => 1,
    ),
    array(
        "id" => 246,
        "pid" => 228,
        "title" => "节点管理",
        "icon" => "fa fa-list",
        "href" => "system.node/index",
        "params" => "",
        "target" => "_self",
        "sort" => 9,
        "status" => 1,
    ),
    array(
        "id" => 247,
        "pid" => 228,
        "title" => "配置管理",
        "icon" => "fa fa-asterisk",
        "href" => "system.config/index",
        "params" => "",
        "target" => "_self",
        "sort" => 8,
        "status" => 1,
    ),
    array(
        "id" => 248,
        "pid" => 228,
        "title" => "上传管理",
        "icon" => "fa fa-arrow-up",
        "href" => "system.uploadfile/index",
        "params" => "",
        "target" => "_self",
        "sort" => 0,
        "status" => 1,
    ),
    array(
        "id" => 249,
        "pid" => 0,
        "title" => "商城管理",
        "icon" => "fa fa-list",
        "href" => "",
        "params" => "",
        "target" => "_self",
        "sort" => 0,
        "status" => 1,
    ),
    array(
        "id" => 250,
        "pid" => 249,
        "title" => "商品分类",
        "icon" => "fa fa-calendar-check-o",
        "href" => "mall.cate/index",
        "params" => "",
        "target" => "_self",
        "sort" => 0,
        "status" => 1,
    ),
    array(
        "id" => 251,
        "pid" => 249,
        "title" => "商品管理",
        "icon" => "fa fa-list",
        "href" => "mall.goods/index",
        "params" => "",
        "target" => "_self",
        "sort" => 0,
        "status" => 1,
    ),
    array(
        "id" => 252,
        "pid" => 228,
        "title" => "快捷入口",
        "icon" => "fa fa-list",
        "href" => "system.quick/index",
        "params" => "",
        "target" => "_self",
        "sort" => 0,
        "status" => 1,
    ),
    array(
        "id" => 253,
        "pid" => 228,
        "title" => "日志管理",
        "icon" => "fa fa-connectdevelop",
        "href" => "debug.log/index",
        "params" => "",
        "target" => "_self",
        "sort" => 0,
        "status" => 1,
    ),
    array(
        "id" => 254,
        "pid" => 249,
        "title" => "商品标签",
        "icon" => "fa fa-connectdevelop",
        "href" => "mall.tag/index",
        "params" => "",
        "target" => "_self",
        "sort" => 0,
        "status" => 1,
    ),
);


return $ul_system_menu;
