directories:
  output: dist
  buildResources: build
appId: com.5cqbox.app
productName: 5cqbox
files:
  - filter:
      - '!**/.vscode/*'
      - '!src/*'
      - '!electron.vite.config.{js,ts,mjs,cjs}'
      - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
      - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'
asarUnpack:
  - resources/**
win:
  executableName: 5cqbox
  requestedExecutionLevel: requireAdministrator
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: 玩传奇盒子
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
mac:
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    - NSCameraUsageDescription: Application requests access to the device's camera.
    - NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    - NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    - NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
  notarize: false
dmg:
  artifactName: ${name}-${version}.${ext}
linux:
  target:
    - AppImage
    - snap
    - deb
  maintainer: electronjs.org
  category: Utility
appImage:
  artifactName: ${name}-${version}.${ext}
npmRebuild: false
publish:
  provider: generic
  url: https://hz.5cq.net/update/
electronDownload:
  mirror: https://npmmirror.com/mirrors/electron/
releaseInfo:
  releaseNotes: 兼容win7,修复文件解压报错,修复扫描快捷键的无效|登录改造，无需次次扫码
electronVersion: 22.3.27
